name: circulatory-failure
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - tqdm
  - pytorch
  - pip
  - pip:
      - tables
      - jupyterlab